Update MyFirstWorkflow.yml

diff --git a/.github/workflows/MyFirstWorkflow.yml b/.github/workflows/MyFirstWorkflow.yml
--- a/.github/workflows/MyFirstWorkflow.yml
+++ b/.github/workflows/MyFirstWorkflow.yml
@@ -1,23 +1,27 @@
-name: My First Workflow
-on:
-  push: 
-    branches:  
-    - main
-  workflow_dispatch:
+name: Test Action
+on: [push]
+
 jobs:
-  MyFirstJob:
+  test:
     runs-on: ubuntu-latest
     steps:
-      - run: echo " Updating the code "
-      
-      - name: Checkout
+      - name: Checkout repo to use the action locally
         uses: actions/checkout@v4.2.2
 
-      - name: List files in Repository
+      - name: Run my own container action
+        id: my-action
+        uses: ./
+        with:
+          who-to-greet: '@wulfland'
+
+      - name: Debug Output
+        run: echo "DEBUG: Answer received - ${{ steps.my-action.outputs.answer }}"
+
+      - name: Output the answer
+        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
+
+      - name: Test the container
+        if: steps.my-action.outputs.answer != '42'
         run: |
-          echo "The repository ${{github.repository}} contains the following files"
-          tree
-    
-      
-  
-    
+          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+          exit 1
